export const newAndPopularMobile = [
  {
    id: 1,
    icon: '/assets/home/icons/new.svg',
    title: 'Newest',
    isFollowingNumberHidden: true,
    label: 'newest',
  },
  {
    id: 2,
    icon: '/assets/home/icons/popular.svg',
    title: 'Popular',
    isFollowingNumberHidden: true,
    label: 'popular',
  },
  {
    id: 3,
    icon: '/assets/home/icons/follow.svg',
    title: 'Following',
    isFollowingNumberHidden: false,
    label: 'following',
  },
];

export const newAndPopular = [
  {
    id: 1,
    icon: '/assets/home/icons/new.svg',
    title: 'Newest and Recent',
    text: 'Find the latest update',
    isFollowingNumberHidden: true,
    dimensionsOuterSquare: 28,
    dimensionsInnerSquare: 20,
    label: 'newest',
  },
  {
    id: 2,
    icon: '/assets/home/icons/popular.svg',
    title: 'Popular of the day',
    text: 'Shots Featured Today by Creators',
    isFollowingNumberHidden: true,
    dimensionsOuterSquare: 28,
    dimensionsInnerSquare: 20,
    label: 'popular',
  },
  {
    id: 3,
    title: 'Following',
    icon: '/assets/home/icons/follow.svg',
    text: 'Explore from your favorite person',
    isFollowingNumberHidden: false,
    dimensionsOuterSquare: 28,
    dimensionsInnerSquare: 20,
    label: 'following',
  },
];

export const popularTags = [
  {
    id: 1,
    title: 'javascript',
    icon: '/assets/home/icons/javascript.svg',
    noOfPosts: 82645,
    text: 'Posted by this tag',
    isFollowingNumberHidden: true,
    bgColor: 'yellow',
    hashtag: true,
    dimensionsOuterSquare: 28,
    dimensionsInnerSquare: 20,
  },
  {
    id: 2,
    title: 'bitcoin',
    icon: '/assets/home/icons/bitcoin.svg',
    noOfPosts: 65523,
    text: 'Posted | Trending',
    isFollowingNumberHidden: true,
    bgColor: 'red',
    hashtag: true,
    dimensionsOuterSquare: 28,
    dimensionsInnerSquare: 20,
  },
  {
    id: 3,
    title: 'design',
    icon: '/assets/home/icons/design.svg',
    noOfPosts: 45637,
    text: 'Trending in Bangladesh',
    isFollowingNumberHidden: true,
    bgColor: 'blue',
    hashtag: true,
    dimensionsOuterSquare: 28,
    dimensionsInnerSquare: 20,
  },
  {
    id: 4,
    title: 'blogging',
    icon: '/assets/home/icons/blogging.svg',
    noOfPosts: 67645,
    text: 'Posted by this tag',
    isFollowingNumberHidden: true,
    bgColor: 'yellow',
    hashtag: true,
    dimensionsOuterSquare: 28,
    dimensionsInnerSquare: 20,
  },
  {
    id: 5,
    title: 'tutorial',
    icon: '/assets/home/icons/tutorial.svg',
    noOfPosts: 42625,
    text: 'Trending in Bangladesh',
    isFollowingNumberHidden: true,
    bgColor: 'green',
    hashtag: true,
    dimensionsOuterSquare: 28,
    dimensionsInnerSquare: 20,
  },
  {
    id: 6,
    title: 'seo',
    icon: '/assets/home/icons/seo.svg',
    noOfPosts: 55645,
    text: 'Posted by this tag',
    isFollowingNumberHidden: true,
    bgColor: 'purple',
    hashtag: true,
    dimensionsOuterSquare: 28,
    dimensionsInnerSquare: 20,
  },
];

export const pinnedGroups = [
  {
    id: 1,
    title: 'javascript',
    icon: '/assets/home/icons/javascript2.svg',
    noOfPosts: 82645,
    text: 'Posted by this tag',
    hashtag: true,
    isFollowingNumberHidden: true,
    bgColor: 'transparent',
    dimensionsOuterSquare: 32,
    dimensionsInnerSquare: 32,
  },
  {
    id: 2,
    title: 'bitcoin',
    icon: '/assets/home/icons/bitcoin2.svg',
    noOfPosts: 65523,
    text: 'Posted Trending',
    hashtag: true,
    isFollowingNumberHidden: true,
    bgColor: 'transparent',
    dimensionsOuterSquare: 32,
    dimensionsInnerSquare: 32,
  },
  {
    id: 3,
    title: 'design',
    icon: '/assets/home/icons/design2.svg',
    noOfPosts: 45637,
    text: 'Trending in Bangladesh',
    hashtag: true,
    isFollowingNumberHidden: true,
    bgColor: 'transparent',
    dimensionsOuterSquare: 32,
    dimensionsInnerSquare: 32,
  },
  {
    id: 4,
    title: 'blogging',
    icon: '/assets/home/icons/blogging2.svg',
    noOfPosts: 67645,
    text: 'Posted by this tag',
    hashtag: true,
    isFollowingNumberHidden: true,
    bgColor: 'transparent',
    dimensionsOuterSquare: 32,
    dimensionsInnerSquare: 32,
  },
];
